version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies ...
      - npm install
  build:
    commands:
      - echo Build Started on `date`
      - npm run build
      - npm run export
  post_build:
    commands:
      - echo Uploading to S3 ...
      - aws s3 cp --recursive ./out s3://$BUCKET_NAME/
      - echo Invalidating CloudFront cache ...
    #  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: 'out'
